/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Conexion;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class PerfilProfesor extends javax.swing.JPanel {

    /**
     * Creates new form Perfil
     */
    public PerfilProfesor() {
        initComponents();
        guardarPerfilBtn.setVisible(false);
        cancelarPerfilBtn.setVisible(false);
        nombrePerfilTextField.setEditable(false);
        codigoPerfilTextField.setEditable(false);
        nipPerfilTextField.setEditable(false);
        correoPerfilTextField.setEditable(false);
        rolTextField.setEditable(false);
        rolComboBox.setVisible(false);
        tituloPerfilTextField.setEditable(false);
        departamentoTextField.setEditable(false);
        centroTextField.setEditable(false);
        centroComboBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codigoPerfilTextField = new javax.swing.JTextField();
        nombrePerfilTextField = new javax.swing.JTextField();
        nipPerfilTextField = new javax.swing.JTextField();
        correoPerfilTextField = new javax.swing.JTextField();
        cancelarPerfilBtn = new javax.swing.JButton();
        editarPerfilBtn = new javax.swing.JButton();
        guardarPerfilBtn = new javax.swing.JButton();
        rolTextField = new javax.swing.JTextField();
        rolComboBox = new javax.swing.JComboBox<>();
        tituloPerfilTextField = new javax.swing.JTextField();
        departamentoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        centroTextField = new javax.swing.JTextField();
        centroComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 38, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIP");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Título");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departamento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Centro Universitario");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rol");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        codigoPerfilTextField.setBackground(new java.awt.Color(51, 51, 51));
        codigoPerfilTextField.setForeground(new java.awt.Color(255, 255, 255));
        codigoPerfilTextField.setBorder(null);
        add(codigoPerfilTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 500, -1));

        nombrePerfilTextField.setBackground(new java.awt.Color(51, 51, 51));
        nombrePerfilTextField.setForeground(new java.awt.Color(255, 255, 255));
        nombrePerfilTextField.setBorder(null);
        nombrePerfilTextField.setFocusable(false);
        add(nombrePerfilTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 41, 500, -1));

        nipPerfilTextField.setBackground(new java.awt.Color(51, 51, 51));
        nipPerfilTextField.setForeground(new java.awt.Color(255, 255, 255));
        nipPerfilTextField.setBorder(null);
        add(nipPerfilTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 500, -1));

        correoPerfilTextField.setBackground(new java.awt.Color(51, 51, 51));
        correoPerfilTextField.setForeground(new java.awt.Color(255, 255, 255));
        correoPerfilTextField.setBorder(null);
        add(correoPerfilTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 500, -1));

        cancelarPerfilBtn.setBackground(new java.awt.Color(51, 51, 51));
        cancelarPerfilBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarPerfilBtn.setText("Cancelar");
        cancelarPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPerfilBtnActionPerformed(evt);
            }
        });
        add(cancelarPerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        editarPerfilBtn.setBackground(new java.awt.Color(51, 51, 51));
        editarPerfilBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarPerfilBtn.setText("Editar");
        editarPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerfilBtnActionPerformed(evt);
            }
        });
        add(editarPerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 38, -1, -1));

        guardarPerfilBtn.setBackground(new java.awt.Color(51, 51, 51));
        guardarPerfilBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarPerfilBtn.setText("Guardar");
        guardarPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPerfilBtnActionPerformed(evt);
            }
        });
        add(guardarPerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 38, -1, -1));

        rolTextField.setBackground(new java.awt.Color(51, 51, 51));
        rolTextField.setForeground(new java.awt.Color(255, 255, 255));
        rolTextField.setBorder(null);
        add(rolTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 490, -1));

        rolComboBox.setBackground(new java.awt.Color(51, 51, 51));
        rolComboBox.setForeground(new java.awt.Color(255, 255, 255));
        rolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", "Administrador" }));
        add(rolComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 490, -1));

        tituloPerfilTextField.setBackground(new java.awt.Color(51, 51, 51));
        tituloPerfilTextField.setForeground(new java.awt.Color(255, 255, 255));
        tituloPerfilTextField.setBorder(null);
        add(tituloPerfilTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 500, -1));

        departamentoTextField.setBackground(new java.awt.Color(51, 51, 51));
        departamentoTextField.setForeground(new java.awt.Color(255, 255, 255));
        departamentoTextField.setBorder(null);
        add(departamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 500, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        centroTextField.setBackground(new java.awt.Color(51, 51, 51));
        centroTextField.setForeground(new java.awt.Color(255, 255, 255));
        centroTextField.setBorder(null);
        add(centroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 500, -1));

        centroComboBox.setBackground(new java.awt.Color(51, 51, 51));
        centroComboBox.setForeground(new java.awt.Color(255, 255, 255));
        centroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro Universitario de Arte, Arquitectura y Diseñio (CUAAD)", "Centro Universitario de Ciencias Biologicas y Agropecuarias (CUCBA)", "Centro Universitario de Ciencias Economico-Administrativas (CUCEA)", "Centro Universitario de Ciencias Exactas e ingenierias (CUCEI)", "Centro Universitario de Ciencias de la Salud (CUCS)", "Centro Universitario de Ciencias Sociales y Humanidades (CUCSH)", "Centro Universitario de Tonala (CUTonala)", "Centro Universitario de Tlajomulco (CUTlajomulco)", "Centro Universitario de Tlaquepaque (CUTlaquepaque)", "Centro Universitario de Los Altos (CUAltos)", "Centro Universitario de Chapala (CUChapala)", "Centro Universitario de la Cienega (CUCienega)", "Centro Universitario de la Costa (CUCosta)" }));
        centroComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centroComboBoxActionPerformed(evt);
            }
        });
        add(centroComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 490, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPerfilBtnActionPerformed
        // TODO add your handling code here:
        guardarPerfilBtn.setVisible(false);
        cancelarPerfilBtn.setVisible(false);
        editarPerfilBtn.setVisible(true);
        nombrePerfilTextField.setFocusable(false);
        nombrePerfilTextField.setForeground(new Color(255, 255, 255));
        codigoPerfilTextField.setFocusable(false);
        codigoPerfilTextField.setForeground(new Color(255, 255, 255));
        nipPerfilTextField.setFocusable(false);
        nipPerfilTextField.setForeground(new Color(255, 255, 255));
        correoPerfilTextField.setFocusable(false);
        correoPerfilTextField.setForeground(new Color(255, 255, 255));
        rolComboBox.setVisible(false);
        rolTextField.setVisible(true);
        nombrePerfilTextField.setEditable(false);
        codigoPerfilTextField.setEditable(false);
        nipPerfilTextField.setEditable(false);
        correoPerfilTextField.setEditable(false);
        rolTextField.setEditable(false);
        tituloPerfilTextField.setEditable(false);
        departamentoTextField.setEditable(false);
        centroTextField.setEditable(false);
    }//GEN-LAST:event_cancelarPerfilBtnActionPerformed

    private void editarPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerfilBtnActionPerformed
        // TODO add your handling code here:
        codigoPerfilTextField.setFocusable(true);
        codigoPerfilTextField.setForeground(new Color(0, 204, 0));
        codigoPerfilTextField.setEditable(true);
        nombrePerfilTextField.setFocusable(true);
        nombrePerfilTextField.setForeground(new Color(0, 204, 0));
        nombrePerfilTextField.setEditable(true);
        nipPerfilTextField.setFocusable(true);
        nipPerfilTextField.setForeground(new Color(0, 204, 0));
        nipPerfilTextField.setEditable(true);
        correoPerfilTextField.setFocusable(true);
        correoPerfilTextField.setForeground(new Color(0, 204, 0));
        correoPerfilTextField.setEditable(true);
        editarPerfilBtn.setVisible(false);
        cancelarPerfilBtn.setVisible(true);
        guardarPerfilBtn.setVisible(true);
        rolComboBox.setVisible(true);
        rolTextField.setVisible(false);
        rolTextField.setEditable(true);
        rolComboBox.setSelectedItem(rolTextField.getText());
        tituloPerfilTextField.setFocusable(true);
        tituloPerfilTextField.setForeground(new Color(0, 204, 0));
        tituloPerfilTextField.setEditable(true);
        departamentoTextField.setFocusable(true);
        departamentoTextField.setForeground(new Color(0, 204, 0));
        departamentoTextField.setEditable(true);
        centroComboBox.setVisible(true);
        centroTextField.setVisible(false);
        centroTextField.setEditable(true);
        centroComboBox.setSelectedItem(centroTextField.getText());
    }//GEN-LAST:event_editarPerfilBtnActionPerformed

    private void guardarPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPerfilBtnActionPerformed
        // TODO add your handling code here:
        PerfilProfesor actualPerfil = new PerfilProfesor();
        Conexion con = new Conexion();
        PanelProfesor d = new PanelProfesor();
        actualPerfil.nombrePerfilTextField.setText(nombrePerfilTextField.getText());
        actualPerfil.codigoPerfilTextField.setText(codigoPerfilTextField.getText());
        actualPerfil.nipPerfilTextField.setText(nipPerfilTextField.getText());
        actualPerfil.correoPerfilTextField.setText(correoPerfilTextField.getText());
        actualPerfil.rolTextField.setText((String) rolComboBox.getSelectedItem());
        
        try {
            // Actualizacion realizada desde el controlador
            con.conexionProfesor(actualPerfil.codigoPerfilTextField.toString(), d, 1, actualPerfil);
            // Una vez que realizamos la actualizacion, regresamos los campos a solo lectura
            this.nombrePerfilTextField.setFocusable(false);
            this.nombrePerfilTextField.setForeground(new Color(255, 255, 255));       
            this.nipPerfilTextField.setFocusable(false);
            this.nipPerfilTextField.setForeground(new Color(255, 255, 255));
            this.correoPerfilTextField.setFocusable(false);
            this.correoPerfilTextField.setForeground(new Color(255, 255, 255));
            this.rolComboBox.setVisible(false);
            this.rolTextField.setText((String) this.rolComboBox.getSelectedItem());
            this.rolTextField.setVisible(true);
            this.rolTextField.setEditable(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PerfilProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarPerfilBtnActionPerformed

    private void centroComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centroComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_centroComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelarPerfilBtn;
    public javax.swing.JComboBox<String> centroComboBox;
    public javax.swing.JTextField centroTextField;
    public javax.swing.JTextField codigoPerfilTextField;
    public javax.swing.JTextField correoPerfilTextField;
    public javax.swing.JTextField departamentoTextField;
    public javax.swing.JButton editarPerfilBtn;
    public javax.swing.JButton guardarPerfilBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nipPerfilTextField;
    public javax.swing.JTextField nombrePerfilTextField;
    public javax.swing.JComboBox<String> rolComboBox;
    public javax.swing.JTextField rolTextField;
    public javax.swing.JTextField tituloPerfilTextField;
    // End of variables declaration//GEN-END:variables
}
